#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mc")]
	public partial class mcDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public mcDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["mcConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public mcDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mcDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mcDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mcDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Challenge> Challenges
		{
			get
			{
				return this.GetTable<Challenge>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Challenge")]
	public partial class Challenge
	{
		
		private System.Nullable<int> _chanID;
		
		private System.Nullable<int> _chanType;
		
		private System.Nullable<int> _salary;
		
		private System.Nullable<bool> _open;
		
		private System.Nullable<System.DateTime> _publishTime;
		
		private System.Nullable<bool> _status;
		
		public Challenge()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chanID", DbType="Int")]
		public System.Nullable<int> chanID
		{
			get
			{
				return this._chanID;
			}
			set
			{
				if ((this._chanID != value))
				{
					this._chanID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chanType", DbType="Int")]
		public System.Nullable<int> chanType
		{
			get
			{
				return this._chanType;
			}
			set
			{
				if ((this._chanType != value))
				{
					this._chanType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="Int")]
		public System.Nullable<int> salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this._salary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[open]", Storage="_open", DbType="Bit")]
		public System.Nullable<bool> open
		{
			get
			{
				return this._open;
			}
			set
			{
				if ((this._open != value))
				{
					this._open = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> publishTime
		{
			get
			{
				return this._publishTime;
			}
			set
			{
				if ((this._publishTime != value))
				{
					this._publishTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
